# Usa a imagem mais recente do MySQL
FROM mysql:latest as builder 

RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

# Define a password do root
ENV MYSQL_ROOT_PASSWORD=12345678

# Copia o arquivo init.sql para o diretório padrão
COPY init.sql/init.sql /docker-entrypoint-initdb.d/

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]

FROM mysql:latest

COPY --from=builder /initialized-db /var/lib/mysql