version: '3.8'

services:
  database:
    container_name: comercio-dev-db
    image: mysql:8.0  # Usa uma versão fixa para evitar surpresas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: comerciodev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/  # Monta corretamente a pasta
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dev_user", "-pdev_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  nodejs:
    container_name: comercio-dev
    build: .
    restart: always
    env_file:
      - ./environment/dev.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Mantém código sincronizado entre host e container
    command: "npm start"

volumes:
  mysql-data:
    driver: local