FROM docker.io/library/node:18-slim

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

RUN npm install --force

ENV HOST=0.0.0.0 PORT=3000

COPY --chown=node . .

EXPOSE ${PORT}
CMD [ "npm", "start" ]